# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Gradle build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Build with Gradle
      run: gradle clean test
    - name: Download Reports
      continue-on-error: true
      uses: actions/checkout@v2
    - name: Download Reports
      continue-on-error: true
      uses: actions/download-artifact@v3
      with:
        name: my-artifact
        path: target
    - name: Display structure of downloaded files
      run: ls -R
